[package]
name = "typhoon"
version = "0.1.0"
edition = "2024"
description = "A sample implementation of TYPHOON protocol"
authors = [
    "Alexander Sergeev <aleksandr.sergeev.dm@gmail.com>"
]


[features]
default = ["software", "fast", "server", "client"]
# default = ["hardware", "full", "server", "client"]
hardware = ["aes-gcm"]
software = ["chacha20poly1305"]
fast = ["classic-mceliece-rust"]
full = ["curve25519-elligator2"]
server = []
client = []


[dependencies]
aes-gcm = { version = "^0.10.3", optional = true }
sha2 = "^0.10.9"
chacha20poly1305 = { version = "^0.10.1", optional = true }
classic-mceliece-rust = { version = "^3.1.0", optional = true}
x25519-dalek = { version = "^2.0.1", features = ["static_secrets"] }
ed25519-dalek = "^2.2.0"
curve25519-elligator2 = { version = "=0.1.0-alpha.2", features = ["elligator2"], default-features = false, optional = true}
hkdf = { version = "^0.12.4", features = ["std"] }
lazy_static = "^1.5.0"
rand = "^0.8.5"
simple-error = "^0.3.1"
tokio = { version = "^1.47.1", features = ["full"] }
