[package]
name = "typhoon"
version = "0.1.0"
edition = "2024"
description = "A sample implementation of TYPHOON protocol"
authors = [
    "Alexander Sergeev <aleksandr.sergeev.dm@gmail.com>"
]


[features]
default = ["software", "fast", "server", "client", "tokio"]
hardware = ["dep:aes", "dep:aes-gcm", "dep:ctr"]
software = ["dep:chacha20", "dep:chacha20poly1305"]
fast = []
full = []
server = []
client = []
async-std = ["dep:async-channel", "dep:async-io", "dep:async-lock"]
tokio = ["dep:tokio"]


[dependencies]
aes = { version = "^0.8.4", optional = true }
aes-gcm = { version = "^0.10.3", features = ["std"], optional = true }
async-channel = { version = "^2.5.0", optional = true }
async-io = { version = "^2.6.0", optional = true }
async-lock = { version = "^3.4.2", optional = true }
bitflags = "^2.10.0"
blake3 = "^1.8.3"
cfg-if = "^1.0.4"
crossbeam = "^0.8.4"
ctr = { version = "^0.9.2", optional = true }
chacha20 = { version = "^0.9.1", optional = true }
chacha20poly1305 = { version = "^0.10.1", features = ["std"], optional = true }
classic-mceliece-rust = { version = "^3.1.0", features = ["mceliece348864"] }
constant_time_eq = "^0.4.2"
ed25519-dalek = "^2.2.0"
generic-array = "^1.3.5"
lazy_static = "^1.5.0"
log = "^0.4.29"
rand = "^0.8.5"
thiserror = "^2.0.18"
tokio = { version = "^1.47.1", features = ["net", "sync"], optional = true }
x25519-dalek = { version = "^2.0.1", features = ["static_secrets"] }
