name: RUST

permissions:
  contents: read

on:
  push:
    paths:
      - 'typhoon/**'
      - '.github/workflows/rust.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  typhoon-crate-build:
    name: Build and Test TYPHOON Rust Crate
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - image: windows-2025
            target: x86_64-pc-windows-msvc
          - image: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - image: windows-11-arm
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Rust ğŸ¦€
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.89.0"
          target: ${{ matrix.target }}
          rust-src-dir: typhoon
          override: true

      - name: Build TYPHOON Crate ğŸ—ï¸
        working-directory: typhoon
        run: cargo build

      - name: Test TYPHOON Crate ğŸ§ª
        working-directory: typhoon
        run: cargo test
